apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: my-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: python-playground-ui-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: External
    external:
      metricName: custom.googleapis.com|nginx.googleapis.com/request_count
      targetAverageValue: "100"