apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-playground-ui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-playground-ui
  template:
    metadata:
      labels:
        app: python-playground-ui
    spec:
      containers:
        - name: python-playground-ui
          image: gcr.io/caas-390503/python-playground-ui@sha256:ed25846706cb53a9eb6d64cb9a0437bfc914d108b090864f40b6379c3a028fc6
          ports:
            - containerPort: 80
