apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-playground-ui-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-playground-ui
  template:
    metadata:
      labels:
        app: python-playground-ui
    spec:
      containers:
        - name: python-playground-ui
          image: gcr.io/caas-390503/python-playground-ui@sha256:3c7df8d21cf7e5d60ccc59624b1018240b2eefd1d59dd26d660ea6eab66b370c
          ports:
            - containerPort: 80
