apiVersion: v1
kind: Service
metadata:
  name: python-playground-ui-service
  annotations:
    networking.gke.io/max-rate-per-endpoint: "10"
spec:
  selector:
    app: python-playground-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer